version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    image: 'postgres:latest'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=14g9flbf'
      - 'POSTGRES_DB=weather-sensor-api'

  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"


  kafka:
        image: wurstmeister/kafka
        ports:
          - "9092:9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPICS: "test_topic:1:1"