version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_DB=weather-sensor-api'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080

